### ISSUE TITLE
A memory leak issue

### ISSUE THREAD

**Issue by ghost** [Gawdl3y/discord-moosik#1]
I have been told that this is a memory leak,

https://github.com/Gawdl3y/discord-moosik/blob/master/src/commands/music/skip.js#L103

Uncaught Promise Error:  RangeError: Maximum call stack size exceeded
    at setTimeout (/root/shotz/commands/musicskip.js:76:14)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)
    at setTimeout (/root/shotz/commands/musicskip.js:71:17)

Not sure what to do tho

**Comment by Gawdl3y** [comment]
It's not a memory leak, but rather function calls being nested too deeply. Likely an issue with your own code.
